export const users = [
  {
    id: 1,
    name: 'Alice Johnson',
    email: 'alice.j@example.com',
    phone: '123-456-7890',
    bio: 'Frontend developer with a passion for creating beautiful and intuitive user interfaces. Loves hiking and photography.',
    imageUrl: 'https://i.pravatar.cc/150?img=1',
  },
  {
    id: 2,
    name: 'Bob Williams',
    email: 'bob.w@example.com',
    phone: '234-567-8901',
    bio: 'Backend engineer specializing in scalable systems and cloud infrastructure. Enjoys playing chess and cooking.',
    imageUrl: 'https://i.pravatar.cc/150?img=2',
  },
  {
    id: 3,
    name: 'Charlie Brown',
    email: 'charlie.b@example.com',
    phone: '345-678-9012',
    bio: 'UI/UX designer focused on user-centered design principles. Avid reader and traveler.',
    imageUrl: 'https://i.pravatar.cc/150?img=3',
  },
  {
    id: 4,
    name: 'Diana Miller',
    email: 'diana.m@example.com',
    phone: '456-789-0123',
    bio: 'Full-stack developer who enjoys tackling complex problems. Spends free time kayaking and building custom keyboards.',
    imageUrl: 'https://i.pravatar.cc/150?img=4',
  },
  {
    id: 5,
    name: 'Ethan Davis',
    email: 'ethan.d@example.com',
    phone: '567-890-1234',
    bio: 'Project manager ensuring projects are delivered on time and on budget. Also a certified yoga instructor.',
    imageUrl: 'https://i.pravatar.cc/150?img=5',
  },
  {
    id: 6,
    name: 'Fiona Garcia',
    email: 'fiona.g@example.com',
    phone: '678-901-2345',
    bio: 'Data scientist who loves finding patterns in data. Enjoys cycling and painting watercolors.',
    imageUrl: 'https://i.pravatar.cc/150?img=6',
  },
  {
    id: 7,
    name: 'George Rodriguez',
    email: 'george.r@example.com',
    phone: '789-012-3456',
    bio: 'DevOps engineer passionate about automation and CI/CD pipelines. A big fan of sci-fi movies.',
    imageUrl: 'https://i.pravatar.cc/150?img=7',
  },
  {
    id: 8,
    name: 'Hannah Wilson',
    email: 'hannah.w@example.com',
    phone: '890-123-4567',
    bio: 'Mobile developer for both iOS and Android platforms. Loves dogs and volunteers at a local animal shelter.',
    imageUrl: 'https://i.pravatar.cc/150?img=8',
  },
];
