export const users = [
  {
    id: 1,
    name: 'Alice Johnson',
    email: 'alice.j@example.com',
    phone: '123-456-7890',
    bio: "A civil engineering graduate from the University of Waterloo, Alice founded 'TerraForm Inc.', a multi-million dollar construction tech company that revolutionizes urban infrastructure projects with AI-driven planning tools.",
    imageUrl: 'https://i.pravatar.cc/150?img=1',
  },
  {
    id: 2,
    name: 'Bob Williams',
    email: 'bob.w@example.com',
    phone: '234-567-8901',
    bio: "With a degree in software engineering from the University of British Columbia, Bob launched 'QuantumLeap AI,' a leading firm in machine learning solutions, now valued at over $50 million.",
    imageUrl: 'https://i.pravatar.cc/150?img=2',
  },
  {
    id: 3,
    name: 'Charlie Brown',
    email: 'charlie.b@example.com',
    phone: '345-678-9012',
    bio: "An electrical engineering alumnus from McGill University, Charlie is the founder of 'Volt-Tech Renewables,' a company at the forefront of sustainable energy, specializing in next-generation solar panel technology.",
    imageUrl: 'https://i.pravatar.cc/150?img=3',
  },
  {
    id: 4,
    name: 'Diana Miller',
    email: 'diana.m@example.com',
    phone: '456-789-0123',
    bio: "After graduating in mechanical engineering from Queen's University, Diana created 'AeroDynamics,' a multi-million dollar enterprise that designs and manufactures cutting-edge drones for logistical and agricultural use.",
    imageUrl: 'https://i.pravatar.cc/150?img=4',
  },
  {
    id: 5,
    name: 'Ethan Davis',
    email: 'ethan.d@example.com',
    phone: '567-890-1234',
    bio: "A computer engineering graduate from the University of Alberta, Ethan co-founded 'CyberSecure,' a cybersecurity firm that protects major financial institutions and is now a leader in the industry.",
    imageUrl: 'https://i.pravatar.cc/150?img=5',
  },
  {
    id: 6,
    name: 'Fiona Garcia',
    email: 'fiona.g@example.com',
    phone: '678-901-2345',
    bio: "Fiona, a biomedical engineering graduate from McMaster University, is the CEO of 'MedInnovate,' a company that develops groundbreaking medical devices and has secured millions in funding.",
    imageUrl: 'https://i.pravatar.cc/150?img=6',
  },
  {
    id: 7,
    name: 'George Rodriguez',
    email: 'george.r@example.com',
    phone: '789-012-3456',
    bio: "Holding a degree in materials engineering from the University of Toronto, George started 'Polymeric Solutions,' a company that creates advanced, eco-friendly polymers for manufacturing, reaching an eight-figure valuation.",
    imageUrl: 'https://i.pravatar.cc/150?img=7',
  },
  {
    id: 8,
    name: 'Hannah Wilson',
    email: 'hannah.w@example.com',
    phone: '890-123-4567',
    bio: "As a systems design engineering graduate from the University of Waterloo, Hannah founded 'ConnectSphere,' a SaaS platform for remote team collaboration that serves thousands of businesses worldwide.",
    imageUrl: 'https://i.pravatar.cc/150?img=8',
  },
  {
    id: 9,
    name: 'Ian Martinez',
    email: 'ian.m@example.com',
    phone: '901-234-5678',
    bio: "An alumnus of Dalhousie University with a degree in chemical engineering, Ian founded 'BioSynth Labs,' a biotech firm that develops sustainable alternatives to plastics, recently valued at over $20 million.",
    imageUrl: 'https://i.pravatar.cc/150?img=9',
  },
];